[project]
name = "tarea3ci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "librosa>=0.11.0",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "setuptools<70",
    "tensorflow-hub>=0.16.1",
    "tensorflow[and-cuda]>=2.21.0",
    "tqdm>=4.67.3",
]
